version: '3'

services:
  app:
    image: node:18
    working_dir: /code
    command:
      - bash
      - -c
      - npm run dev -- --host --port 8000
    ports: [8600:8000]
    volumes:
      - .:/code

  db:
    image: mongo
